# Generated by Django 2.1 on 2020-10-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egystoreapp', '0004_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
